In [1]:
import pandas as pd

In [3]:
mag_nodes_df = pd.read_csv("../data/01_csv_graphs/mag/nodes.csv")

/var/folders/rv/0brfn3g10137qh8fcq6ch2c00000gn/T/ipykernel_13874/3386718327.py:1: DtypeWarning: Columns (3,11,12,13,15,16,23,25,29,32,34,35,36,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  mag_nodes_df = pd.read_csv("../data/01_csv_graphs/mag/nodes.csv")

In [10]:
cleaned_groups = {name: group.dropna(axis=1, how='all') 
                  for name, group in mag_nodes_df.groupby('type')}

In [12]:
cleaned_groups.keys()

dict_keys(['author', 'field_of_study', 'institution', 'paper'])

In [20]:
cleaned_groups['field_of_study']

,id,mag_id,Rank,DisplayName,PaperCount,CitationCount,type,new_id,Level,index
1113255,0,4250,15252.0,Sign function,820.0,7533.0,field_of_study,1113255,3.0,1113255
1113256,1,12843,11980.0,Gravitational singularity,29654.0,338027.0,field_of_study,1113256,2.0,1113256
1113257,2,20288,11787.0,Superstring theory,6772.0,160417.0,field_of_study,1113257,3.0,1113257
1113258,3,37253,12134.0,Complete intersection,2428.0,27280.0,field_of_study,1113258,2.0,1113258
1113259,4,39854,13346.0,Torque converter,15356.0,91481.0,field_of_study,1113259,3.0,1113259
...,...,...,...,...,...,...,...,...,...,...
1172719,59960,2994609373,-1.0,-1.0,-1.0,-1.0,field_of_study,1172719,-1.0,1172719
1172720,59961,2994609795,-1.0,-1.0,-1.0,-1.0,field_of_study,1172720,-1.0,1172720
1172721,59962,2994609957,-1.0,-1.0,-1.0,-1.0,field_of_study,1172721,-1.0,1172721
1172722,59963,2994610206,-1.0,-1.0,-1.0,-1.0,field_of_study,1172722,-1.0,1172722
1172723,59964,2994610307,-1.0,-1.0,-1.0,-1.0,field_of_study,1172723,-1.0,1172723

In [19]:
cleaned_groups['institution']

,id,mag_id,Rank,DisplayName,PaperCount,CitationCount,type,new_id,index
1104554,0,9507,11616.0,Sangji University,1259.0,10636.0,institution,1104554,1104554
1104555,1,19722,11471.0,Ateneo de Manila University,1467.0,8557.0,institution,1104555,1104555
1104556,2,41870,11530.0,Instituto Militar de Engenharia,1289.0,9985.0,institution,1104556,1104556
1104557,3,43886,13361.0,Sapientia University,265.0,1173.0,institution,1104557,1104557
1104558,4,46017,10780.0,KahramanmaraÅŸ SÃ¼tÃ§Ã¼ Ä°mam University,1928.0,20112.0,institution,1104558,1104558
...,...,...,...,...,...,...,...,...,...
1113250,8735,2961216182,-1.0,-1,-1.0,-1.0,institution,1113250,1113250
1113251,8736,2972652528,-1.0,-1,-1.0,-1.0,institution,1113251,1113251
1113252,8737,3004594783,-1.0,-1,-1.0,-1.0,institution,1113252,1113252
1113253,8738,3005327000,-1.0,-1,-1.0,-1.0,institution,1113253,1113253
1113254,8739,3006985408,-1.0,-1,-1.0,-1.0,institution,1113254,1113254

In [17]:
cleaned_groups['author']

,id,mag_id,Rank,DisplayName,LastKnownAffiliationId,PaperCount,CitationCount,type,new_id,index
0,0,29650,16355.0,Alexander Wagenpfahl,2.597410e+07,16.0,982.0,author,0,0
1,1,39382,18658.0,Torben Jabben,3.151278e+07,8.0,21.0,author,1,1
2,2,41399,13895.0,Igor A. Abrikosov,1.021347e+08,409.0,7624.0,author,2,2
3,3,46586,15055.0,Lars Goerigk,1.657796e+08,47.0,6816.0,author,3,3
4,4,60751,16821.0,Yu. V. Kaletina,1.313323e+09,45.0,105.0,author,4,4
...,...,...,...,...,...,...,...,...,...,...
1104549,1134644,3012560199,-1.0,-1,-1.000000e+00,-1.0,-1.0,author,1104549,1104549
1104550,1134645,3012560861,-1.0,-1,-1.000000e+00,-1.0,-1.0,author,1104550,1104550
1104551,1134646,3012560907,-1.0,-1,-1.000000e+00,-1.0,-1.0,author,1104551,1104551
1104552,1134647,3012561154,-1.0,-1,-1.000000e+00,-1.0,-1.0,author,1104552,1104552
1104553,1134648,3012561163,-1.0,-1,-1.000000e+00,-1.0,-1.0,author,1104553,1104553

In [22]:
cleaned_groups['paper']

,id,mag_id,type,new_id,PaperRank,DocType,OriginalTitle,BookTitle,Year,Date,...,ConferenceInstancesDisplayName,ConferenceSeriesId.1,Location,StartDate,EndDate,ConferenceInstancesPaperCount,ConferenceInstanceCitationCount,title,abstract,index
1172724,1,274683,paper,1172724,21080.0,Journal,The Impact of Refractory Material Properties o...,-1.0,2012.0,2012-01-01,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,The Impact of Refractory Material Properties o...,Many divertor design studies for future fusion...,1172724
1172725,2,539484,paper,1172725,21894.0,Journal,Observing signals of the bulk matter Randall-S...,-1.0,2012.0,2012-01-19,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,Observing signals of the bulk matter Randall-S...,The bulk matter Randall-Sundrum (RS) model is ...,1172725
1172726,4,729144,paper,1172726,21059.0,Journal,Bounding the Zâ€²tc coupling from mixing and sin...,-1.0,2011.0,2011-04-01,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,Bounding the Zâ€²tc coupling from mixing and sin...,"In this work, the Z'tc coupling is bounded by ...",1172726
1172727,5,784567,paper,1172727,20307.0,Journal,Distinct magnetism in ultrathin epitaxial NiFe...,-1.0,2011.0,2011-10-20,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,Distinct magnetism in ultrathin epitaxial NiFe...,"Michael Foerster,1 Jose Manuel Rebled,1,2 Soni...",1172727
1172728,6,892929,paper,1172728,20363.0,Journal,Observation of a new electronic state of CO pe...,-1.0,2014.0,2014-10-14,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,Observation of a new electronic state of CO pe...,A.H. was supported by\r\nGrant No. 648.000.002...,1172728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1872963,736379,3012372333,paper,1872963,-1.0,-1,-1,-1,-1.0,-1,...,-1,-1.0,-1,-1,-1,-1.0,-1.0,Electronic structures of doped BaFe 2 As 2 mat...,Using virtual crystal approximation and super-...,1872963
1872964,736384,3012443890,paper,1872964,-1.0,-1,-1,-1,-1.0,-1,...,-1,-1.0,-1,-1,-1,-1.0,-1.0,On the Application of Asymptotic Formulae Base...,In this study a technique for the modeling of ...,1872964
1872965,736385,3012445851,paper,1872965,-1.0,-1,-1,-1,-1.0,-1,...,-1,-1.0,-1,-1,-1,-1.0,-1.0,FCC Physics Opportunities,This volume of the Conceptual Design Report is...,1872965
1872966,736387,3012519720,paper,1872966,-1.0,-1,-1,-1,-1.0,-1,...,-1,-1.0,-1,-1,-1,-1.0,-1.0,Multiband superconductivity in BiS2-based laye...,A mean-field treatment is presented of a squar...,1872966
1872967,736388,3012554801,paper,1872967,-1.0,-1,-1,-1,-1.0,-1,...,-1,-1.0,-1,-1,-1,-1.0,-1.0,Dynamics of coronal rain and descending plasma...,Observations of active regions and limb promin...,1872967